### ISSUE TITLE
No explanation of required Maven dependencies

### ISSUE THREAD

**Issue by dragetd** [spring-guides/gs-contract-rest#12]
The 'initial' directory has the rest-service project with the required dependencies commented out in the pom.xml:

https://github.com/spring-guides/gs-contract-rest/blob/09172e862ac80e07be40589f0a5e5ea179685828/initial/contract-rest-service/pom.xml#L31-L42

The comment also includes wiremock, which seems to be not needed.
The guide does not mention the required dependencies or explains that these comments can be removed. In contrast, it mentions the plugin to add to the Maven plugins.

This is somehow confusing. My suggestion would be: Remove the commented out lines from the 'initial' example and describe which dependency and plugin are required in the guide instead.

If you agree, I am happy to create a PR.

**Comment by marcingrzejszczak** [comment]
I agree, makes perfect sense.
