### ISSUE TITLE
Initial example cloud include test-resource directory

### ISSUE THREAD

**Issue by dragetd** [spring-guides/gs-contract-rest#13]
While for an experience programmer this is a no-brainer, not very experienced programmes sometimes struggle to create a resource-directory that is properly defined as a resource directory within their IDE. For example IDEA does not recognize a newly created 'resource' directory as such unless the Maven model is re-imported.

For the sake of the guide being about Spring Cloud Contract, it might help to add `initial/gs-contract-service/src/test/java` and `initial/gs-contract-service/src/test/resource` together with a `.keep` file (so git does not ignore the directory). This might be one less distraction when going through the guide.

If you agree, I can do a PR.

**Comment by marcingrzejszczak** [comment]
I agree, makes perfect sense

**Comment by dragetd** [comment]
Fixed in #19
