### ISSUE TITLE
Gradle wrapper currently not compatible with the latest Java LTS release

### ISSUE THREAD

**Issue by dragetd** [spring-guides/gs-contract-rest#14]
As silly as it is, older Gradle versions do not run on the current LTS JDK 17.

When using JDK 17 as a developer, it is not possible to run any Gradle tasks in this guide. It would be nice if the included wrapper was updated to a version supporting Java 17.

If you agree, I can do a PR.

**Comment by marcingrzejszczak** [comment]
I agree, we should update the wrapper to the latest version
