### ISSUE TITLE
Broken test: Use latest JUnit version of downgrade/upgrade Spring Boot version

### ISSUE THREAD

**Issue by dragetd** [spring-guides/gs-contract-rest#15]
The example project uses Spring Boot 2.4.2. But the spring-boot-test start does not include the JUnit Vintage engine for Junit4 tests: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#user-content-junit-5s-vintage-engine-removed-from-spring-boot-starter-test

AFAIK Spring 2.5 or 2.6 added it back to the starter and should work. If not, the following dependency is required:

```xml
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<scope>test</scope>
		</dependency>
```

Tho I would prefer if the tests were update to use JUint5 instead, which would make them work with Spring-boot-test 2.4, 2.5 and 2.6.

If you agree, I can do a PR.

**Comment by marcingrzejszczak** [comment]
Yeah, we should update them to use JUnit5
