### ISSUE TITLE
Make the contract-rest-client only a client, not a REST service and client

### ISSUE THREAD

**Issue by dragetd** [spring-guides/gs-contract-rest#16]
This one I am less sure about.
But when looking at contract-rest-client, it does implement a full REST service while it is called a 'client'.

For the sake of simplicity of the guide, wouldn't it be better if contract-rest-client only were a CommandlineRunner or something like this, actually only implementing a client and not a server?

Open for suggestions, happy to do a PR, OK with this just just being closed. :)

**Comment by marcingrzejszczak** [comment]
It's a client for the other server, but I get your point. Typically users will have exactly such situation that they have 2 web applications where one is the client of the other. We could maybe leave the current code but provide more documentation explaining the rationale. Are you willing to file a PR with better explanation why this client is a client even though it's a server ;) ?

**Comment by dragetd** [comment]
After thinking about it… yes, this is the usual use-case. Let's keep it as it is. :)
