### ISSUE TITLE
spring boot version upgrade

### ISSUE THREAD

**Issue by gunayus** [spring-guides/gs-contract-rest#2]
Hello @marcingrzejszczak, 

Shall I make it work with spring boot 2.0 and corresponding spring cloud version?

**Comment by marcingrzejszczak** [comment]
@gregturn what's our view on this? I think we should relax with adopting it for 2.0 cause quite a few things might change in the meantime. WDTY?

**Comment by gregturn** [comment]
We aren't moving to 2.0 until GA.

**Comment by gunayus** [comment]
ok, I will do it after GA
