### ISSUE TITLE
The Guide Sample is not consumer driven

### ISSUE THREAD

**Issue by Thinkenterprise** [spring-guides/gs-contract-rest#20]
Sorry but the example confuses me a bit. I thought that in a consumer-driven contract development or test, the consumers create the contracts that the provider has to fulfill. [Martin Fowler Pattern Consumer-Driven Contracts](https://martinfowler.com/articles/consumerDrivenContracts.html) In this example, however, the contract is created by the provider and the stubs are passed to the consumer. Thus, the provider drives the development, not the consumer, right?

**Comment by marcingrzejszczak** [comment]
The example would be consumer-driven if the consumer would file a PR to the producer with a proposal of a contract. Here you can find all possible combinations of consumer / provider driven flows https://docs.spring.io/spring-cloud-contract/docs/current/reference/html/using.html#using

**Comment by Thinkenterprise** [comment]
I don't think the title fits the [Guide](https://spring.io/guides/gs/contract-rest/). I already know that there are different flows. But a beginner does not yet know all of them. Especially not that it is possible to influence the contract via a pull request. But alright, if it's just a suggestion, I'll close the issue.
