### ISSUE TITLE
Unexpected end of file from server; nested exception is java.net.SocketException

### ISSUE THREAD

**Issue by gangakrishh** [spring-guides/gs-contract-rest#5]
getting following error when request sent to client

is this error specific to spring boot 2.0 ?

`{"timestamp":"2018-03-15T14:53:57.414+0000","status":500,"error":"Internal Server Error","message":"I/O error on GET request for \"http://localhost:8000/person/1\": Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server","path":"/message/1"}`

**Comment by juliovera78** [comment]
same

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-contract/issues/809
